---
  - name: Python | install python-pip
    apt: name=python-pip update_cache=yes state=latest
    become: yes
    tags:
      -python

  - name: Python | Update pip
    shell: pip install -U pip
    become: yes
    tags:
      -python

  - name: Python | install python-dev
    apt: name=python-dev update_cache=yes state=latest
    become: yes
    tags:
      -python

  # - name: Python | install swig
  #   apt: name=swig update_cache=yes state=latest
  #   become: yes
  #   tags:
  #     -python

  - name: Python | VirtualEnv
    shell: pip install -U virtualenv
    become: yes
    tags:
      -python

  - name: Python | virtualenvwrapper
    shell: pip install -U virtualenvwrapper
    become: yes
    tags:
      -python

  - name: Python | virtualenvwrapper console support
    apt: pkg="virtualenvwrapper" state="latest"
    become: yes
    tags:
      -python

  - name: Python | install ca-certificates
    package: name="ca-certificates" state=present
    when: ansible_os_family == 'Debian'
    become: yes
    tags:
      -python

  - name: Python | install the Python SNI support packages
    package: name="{{ item }}" state=present
    with_items:
      - python-dev
      - libssl-dev
      - libffi-dev
    when: ansible_os_family == 'Debian'
      and ansible_python_version | version_compare('2.6.0', '>=')
      and ansible_python_version | version_compare('2.7.9', '<')
    become: yes
    tags:
      -python

  - name: Python | install the Python SNI python-pip dependencies.
    pip: name="{{ item }}" state=present
    with_items:
      - pyopenssl
      - ndg-httpsclient
      - pyasn1
    when: ansible_os_family == 'Debian'
      and ansible_python_version | version_compare('2.6.0', '>=')
      and ansible_python_version | version_compare('2.7.9', '<')
    become: yes
    tags:
      -python
