# Credentials:  https://github.com/geerlingguy/ansible-role-repo-epel

---
- name: EPEL | Check if EPEL repo is already configured.
  shell: test -e etc/yum.repos.d/epel.repo
  become: yes
  register: repo_repo_exists
  ignore_errors: true

- name: Install EPEL repo.
  yum: name="https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ epel_release_version | default(ansible_distribution_major_version) }}.noarch.rpm"  state=present
  retries: 5
  delay: 10
  when: repo_repo_exists | failed
  become: yes
  register: result
  until: '"failed" not in result'

- name: Import EPEL GPG key.
  rpm_key: key="/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ epel_release_version | default(ansible_distribution_major_version) }}" state="present"
  when: repo_repo_exists | failed
  become: yes
