---
  - include: tasks_epel.yml

  - name: Python | install python-pip
    yum: name=python-pip update_cache=yes state=latest
    become: yes
    tags:
      -python

  - name: Python | Update pip
    shell: pip install -U pip
    become: yes
    tags:
      -python

  - name: Python | install python-dev
    yum: name=python-devel update_cache=yes state=latest
    become: yes
    tags:
      -python

  # - name: Python | install swig
  #   apt: name=swig update_cache=yes state=latest
  #   become: yes
  #   tags:
  #     -python

  - name: Python | VirtualEnv
    shell: pip install -U virtualenv
    become: yes
    tags:
      -python

  - name: Python | virtualenvwrapper
    shell: pip install -U virtualenvwrapper
    become: yes
    tags:
      -python
